Repository AY2223S2-CS2103-F10-1/tp, pull requests merged in 2023-03, with the labels that each got.

#52 Add use cases in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#55 Add OfficeConnectModelTest
  src/test/java/seedu/address/model/OfficeConnectModelTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: type.Enhancement

#57 Add integration test and fix bug for task and personTask storage
  src/main/java/seedu/address/storage/JsonAdaptedPersonTask.java
  src/main/java/seedu/address/storage/JsonSerializablePersonTaskBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: type.Bug, severity.High

#56 Fix bugs in addtask that caused parser to parse incorrectly
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, severity.High

#58 Add UniqueItemListTest and remove redundant exception class
  src/main/java/seedu/address/model/RepositoryModelManager.java
  src/main/java/seedu/address/model/UniqueItemList.java
  src/main/java/seedu/address/model/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/model/exceptions/ItemNotFoundException.java
  src/main/java/seedu/address/model/mapping/exceptions/DuplicatePersonTaskException.java
  src/main/java/seedu/address/model/mapping/exceptions/PersonTaskNotFoundException.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/test/java/seedu/address/model/ItemStub.java
  src/test/java/seedu/address/model/RepositoryModelManagerTest.java
  src/test/java/seedu/address/model/UniqueItemListTest.java
Labels: type.Enhancement

#59 Fix id related bugs and test cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/shared/Id.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/shared/IdTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#61 Create assign command and test cases for the new classes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Repository.java
  src/main/java/seedu/address/model/shared/Id.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story, priority.High, type.Task

#66 Create DeleteTask command, DeleteTaskCommandParser
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/model/RepositoryModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
Labels: type.Story, priority.High, type.Task

#67 V1.2 "help" feature, include use case in documentation guide
  docs/DeveloperGuide.md
Labels: documentation

#74 Update documentations for addtask command
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/nicklelodeon.md
Labels: documentation, type.Enhancement, priority.Medium

#68 Resolve #65
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Bug, severity.High

#64 Main page gui show detail
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Enhancement, priority.Medium

#81 Implement Review, Reviewtask and Listall features
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListAllCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/commands/ReviewCommand.java
  src/main/java/seedu/address/logic/commands/ReviewTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/ReviewTaskCommandParser.java
  src/main/java/seedu/address/model/Repository.java
  src/main/java/seedu/address/model/RepositoryModelManager.java
  src/main/java/seedu/address/model/mapping/PersonTask.java
  src/main/java/seedu/address/model/person/NameContainsExactKeywordsPredicate.java
  src/main/java/seedu/address/model/task/SubjectContainsExactKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ReviewCommandTest.java
  src/test/java/seedu/address/logic/commands/ReviewTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/ReviewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ReviewTaskCommandParserTest.java
Labels: priority.High, type.Task

#86 Remove redundant method and improved documentation
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation, priority.Medium

#93 Update UI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/CommandBox.css
  src/main/resources/css/DarkTheme.css
  src/main/resources/css/Extensions.css
  src/main/resources/css/HelpWindow.css
  src/main/resources/css/MainWindow.css
  src/main/resources/css/PersonListCard.css
  src/main/resources/css/PersonListView.css
  src/main/resources/css/ResultDisplay.css
  src/main/resources/css/StatusBar.css
  src/main/resources/css/TaskCardView.css
  src/main/resources/css/TaskListView.css
  src/main/resources/images/grassland.png
  src/main/resources/images/wave.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Enhancement

#95 Add Acknowledgements to images used and change default cursor icon
  README.md
  docs/index.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/PersonListCard.css
  src/main/resources/css/ResultDisplay.css
  src/main/resources/css/StatusBar.css
  src/main/resources/images/cursor.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#115 Resolve #106 by Adding the task progress indicator
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/TypicalTasks.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/css/PersonListCard.css
Labels: type.Story, priority.High, type.Enhancement

#113 Fix #112
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/cursor.png
Labels: type.Enhancement, type.Bug, priority.Low, severity.Low

#117 Resolve #116 by give progress a default value
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.Medium, severity.Medium

#118 Update DG for implementations
  docs/DeveloperGuide.md
  docs/images/AddTaskSequenceDiagram.png
  docs/images/DeleteTaskActivityDiagram.png
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: documentation, Project tasks

#121 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/OfficeConnectModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/LogicClassDiagram.png
  docs/images/OfficeComponentManagers.png
  docs/images/OfficeConnectModelClassDiagram.png
  docs/images/OfficeStorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/model/UniqueItemList.java
Labels: type.Task

#123 Add UnassignActivity diagram to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UnassignActivity.puml
  docs/images/UnassignActivity.png
Labels: type.Task

#129 V1.3 DG Help second update
  docs/DeveloperGuide.md
Labels: documentation, priority.Low, Project tasks

#130 Update DG to include details of implementation of Assign command
  docs/DeveloperGuide.md
  docs/diagrams/AssignActivityDiagram.puml
  docs/images/AssignActivityDiagram.png
Labels: documentation, priority.High

#122 Create Filter Command
  docs/DeveloperGuide.md
  docs/images/DeleteTaskActivityDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/TypicalPersons.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: type.Story, priority.High, type.Task

#133 Update assignment repo after deletion of task and person
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/model/OfficeConnectModel.java
  src/main/java/seedu/address/model/RepositoryModelManager.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
Labels: type.Story, priority.High, type.Task

#135 V1.3 quickstart
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/QuickstartCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/QuickstartImages.java
  src/main/java/seedu/address/ui/QuickstartWindow.java
  src/main/resources/css/QuickstartWindow.css
  src/main/resources/images/Ui.png
  src/main/resources/images/quickstart-1.png
  src/main/resources/images/quickstart-2.png
  src/main/resources/images/quickstart-3.png
  src/main/resources/images/quickstart-4.png
  src/main/resources/images/quickstart-5.png
  src/main/resources/images/quickstart-6.png
  src/main/resources/images/quickstart-7.png
  src/main/resources/images/quickstart-8.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuickstartWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/QuickstartCommandTest.java
Labels: type.Story, priority.High, type.Enhancement, type.Task

#137 Add list and filter commands
  src/main/java/seedu/address/logic/commands/IndexCommand.java
  src/main/java/seedu/address/logic/commands/ListAssignment.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/IndexPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/IndexTaskCommandParser.java
  src/main/java/seedu/address/model/util/TypicalPersons.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/css/ResultDisplay.css
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/IndexCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAssignmentTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
Labels: priority.High, type.Enhancement

#144 Add task to person UI indication and improve model cohesion
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/OfficeConnectModel.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/css/PersonListCard.css
  src/main/resources/css/TaskCardView.css
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
Labels: priority.Medium

#147 Update DG with details
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagramTwo.puml
  docs/diagrams/ListTaskSequenceDiagram.puml
  docs/diagrams/style.puml
Labels: documentation

#146 Add datetime
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/shared/Datetime.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/TaskBuilder.java
  src/main/java/seedu/address/model/util/TypicalTasks.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/css/TaskCardView.css
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/model/shared/DatetimeTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: priority.High, type.Enhancement, type.Bug, severity.High

#150 Add nightmode
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/css/CommandBox.css
  src/main/resources/css/DarkTheme.css
  src/main/resources/css/Extensions.css
  src/main/resources/css/HelpWindow.css
  src/main/resources/css/LightTheme.css
  src/main/resources/css/MainWindow.css
  src/main/resources/css/PersonListCard.css
  src/main/resources/css/PersonListView.css
  src/main/resources/css/QuickstartWindow.css
  src/main/resources/css/ResultDisplay.css
  src/main/resources/css/StatusBar.css
  src/main/resources/css/TaskCardView.css
  src/main/resources/css/TaskListView.css
  src/main/resources/images/night_sky.jpg
  src/main/resources/images/night_sky.png
  src/main/resources/images/night_wave.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#154 V1.3 update quickstart and help
  .gitignore
  docs/DeveloperGuide.md
  docs/team/kayyenl.md
  src/main/java/seedu/address/ui/HelpStrings.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/QuickstartImages.java
  src/main/java/seedu/address/ui/QuickstartWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/HelpWindow.css
  src/main/resources/css/QuickstartWindow.css
  src/main/resources/images/quickstart-10.png
  src/main/resources/images/quickstart-11.png
  src/main/resources/images/quickstart-12.png
  src/main/resources/images/quickstart-2.png
  src/main/resources/images/quickstart-3.png
  src/main/resources/images/quickstart-4.png
  src/main/resources/images/quickstart-5.png
  src/main/resources/images/quickstart-6.png
  src/main/resources/images/quickstart-7.png
  src/main/resources/images/quickstart-8.png
  src/main/resources/images/quickstart-9.png
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/QuickstartWindow.fxml
Labels: documentation, type.Story, type.Enhancement, priority.Medium

#156 V1.3 improve and update UG
  README.md
  docs/UserGuide.md
  docs/images/improvedUI.png
  src/main/resources/images/improvedUI.png
Labels: documentation, priority.Medium

#158 Fix UG format
  docs/UserGuide.md
Labels: priority.High, type.Bug, severity.High

#160 Fix UG format findp result and Caution tag
  docs/UserGuide.md
  docs/images/findAlexPaulineResult.png
Labels: priority.High, type.Bug, severity.High

#161 Fix UG format findp for alice
  docs/UserGuide.md
  docs/images/findAlicePaulineResult.png
Labels: priority.High, type.Bug, severity.High

#178 Fix Person and Task list state issue on tags label
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/IndexCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/OfficeConnectModel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
Labels: priority.High

#181 Fix DG format
  docs/UserGuide.md
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, severity.High

#182 Fix UG format and DG Glossary
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.Medium
